#
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
#
# https://dependabot.com/docs/config-file/validator/
#

version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: ci
      include: scope
    reviewers:
      - kare
    assignees:
      - kare
    labels:
      - ci

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: build
      include: scope
    reviewers:
      - kare
    assignees:
      - kare
    labels:
      - build
