---

#
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
# https://dependabot.com/docs/config-file/validator/
#

version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: ci
    labels:
      - ci

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: build
    labels:
      - build
