style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kare/io.github.kare
options:
  commits:
    filters:
      Type:
        - feat
        - docs
        - fix
        - perf
        - refactor
        - chore
        - ci
        - build
  commit_groups:
    sort_by: Custom
    title_order:
        - feat
        - fix
        - docs
        - perf
        - refactor
        - ci
        - build
        - chore
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Chores
      ci: Continuous Integration
      build: Build System
      docs: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - '#'
      - '#gh-'
  refs:
    actions:
      - Closes
      - Fixes
  notes:
    keywords:
      - BREAKING CHANGE
