name: Pre Release

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
    tags: # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
      - '^v([0-9]+)\.([0-9]+)\.([0-9]+)\-(?:alpha|beta)\.[0-9]*$'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.16"
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set environment
        id: env
        run: |
          go install github.com/bvieira/sv4git/v2/cmd/git-sv@v2.4.0
          echo "::set-output name=release_notes_file::$(mktemp)"
      - name: Generate Release Notes
        id: release-notes
        run: |
          git sv release-notes | tee ${{ steps.env.outputs.release_notes_file }}
          echo "::set-output name=release_notes_body::$(cat ${{ steps.env.outputs.release_notes_file }})"
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_SIGNINGKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_SIGNINPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINPASSWORD }}
          ORG_GRADLE_PROJECT_SONATYPEUSERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_SONATYPEPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
        run: |
          ./gradlew --stacktrace publishToSonatype closeAndReleaseSonatypeStagingRepository
      - uses: ncipollo/release-action@v1.8.8
        id: create_release
        with:
          tag: ${{ github.ref }}
          body: ${{ steps.env.outputs.release_notes_body }}
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
