name: Create Release

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.2-beta.13"
      version-next:
        description: "Next version"
        required: true
        default: "0.0.3-beta.14"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - name: Set environment
        id: env
        run: |
          go install github.com/bvieira/sv4git/v2/cmd/git-sv@v2.4.0
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - name: Publish to Maven Central
        run: |
          echo ${{ github.event.inputs.version }}
          SEMVER_REGEX="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"
          function validate_version {
              local version=$1
              if ! [[ "$version" =~ $SEMVER_REGEX ]]; then
                  echo "version $version does not match the semver scheme 'X.Y.Z(-PRERELEASE)(+BUILD)'. See help for more information." 1>&2
                  exit 1
              fi
          }
          validate_version "${{ github.event.inputs.version }}"

          # Update CHANGELOG
          git sv changelog > CHANGELOG.md
          git add CHANGELOG.md
          git commit --message="docs: Update CHANGELOG.md for release ${{ github.event.inputs.version }}"

          # Update version in gradle.properties
          grtmp=$(mktemp)
          sed -E 's/^version=.*$/version = '${{ github.event.inputs.version }}'/g' gradle.properties > "$grtmp"
          mv "$grtmp" gradle.properties
          git add gradle.properties

          # Create release commit
          git commit --message="Release ${{ github.event.inputs.version }}"
          git tag --message="Release ${{ github.event.inputs.version }}" --annotate "v${{ github.event.inputs.version }}"

          # Incerement current version to pre release
          sed -E 's/^version=.*$/version='${{ github.event.inputs.version-next }}'/g' gradle.properties > "$grtmp"
          mv "$grtmp" gradle.properties
          git add gradle.properties
          git commit --message="Prepare for release ${{ github.event.inputs.version-next }}"

          # Push tags
          git push
          git push --tags

