name: Pre Release

defaults:
  run:
    shell: bash --norc --noprofile -e -u -o pipefail -c

on:
  push:
    branches:
      - main
    tags: # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
      - '^v([0-9]+)\.([0-9]+)\.([0-9]+)\-(?:alpha|beta)\.[0-9]*$'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - name: Set environment
        id: env
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/*/}"
          echo "::set-output name=release_notes_file::$(mktemp)"
      - name: Generate Release Notes
        run: |
          go install github.com/bvieira/sv4git/v2/cmd/git-sv@v2.4.0
          git sv release-notes >> ${{ steps.env.outputs.release_notes_file}}
      - name: Publish Release to Maven Central
      - run: |
          #./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      - uses: ncipollo/release-action@v1.8.8
        id: create_release
        with:
          tag: v${{ steps.env.outputs.version }}
          bodyFile: ${{ steps.env.outputs.release_notes_file}}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
