name: Pre Release

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
    tags: # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
      - '^v([0-9]+)\.([0-9]+)\.([0-9]+)\-(?:alpha|beta)\.[0-9]*$'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      - name: Set environment
        id: env
        run: |
          go install github.com/bvieira/sv4git/v2/cmd/git-sv@v2.4.0
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.0
          echo "::set-output name=version::${GITHUB_REF#refs/*/}"

          echo "::set-output name=release_notes_file_sv::$(mktemp)"
          echo "::set-output name=release_notes_file_chglog::$(mktemp)"
          echo "::set-output name=release_notes_file::$(mktemp)"
      - name: Generate Release Notes files
        run: |
          git sv release-notes >> ${{ steps.env.outputs.release_notes_file_sv}}
          git chglog ${{ steps.env.outputs.version }} >> ${{ steps.env.outputs.release_notes_file_chglog}}

          cat ${{ steps.env.outputs.release_notes_file_sv}} >> ${{ steps.env.outputs.release_notes_file}}
          echo "\n\n\n\n# git-sv above and git-chglog below\n\n\n\n" >> ${{ steps.env.outputs.release_notes_file}}
          cat ${{ steps.env.outputs.release_notes_file_chglog}} >> ${{ steps.env.outputs.release_notes_file}}
      - run: |
          #./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      - uses: ncipollo/release-action@v1.8.8
        id: create_release
        with:
          tag: ${{ github.ref }}
          bodyFile: ${{ steps.env.outputs.release_notes_file}}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
